sudo: false
language: node_js
cache:
  directories:
  - "$HOME/.npm"
notifications:
  email: false
install:
  - npm install
node_js:
  - stable
before_install:
  - npm install -g npm@latest
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
