sudo: false
language: node_js
cache:
  directories:
  - "$HOME/.npm"
notifications:
  email: false
install:
  - npm install
node_js:
  - stable
before_install:
  - npm install -g npm@latest
before_script:
  - npm prune
after_success:
  - npm run semantic-release
  - npm run coveralls
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
env:
  global:
    - CC_TEST_REPORTER_ID=ecaf54490a0dc6e57b807e72bae7ace1d7a20a2008129bcdff84136929c25cae
