sudo: false
language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
notifications:
  email: false
node_js:
  - stable
before_install:
  - npm install -g npm@latest
before_script:
  - npm prune
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
  - npm run coveralls
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
